[tool.poetry]
name = "tetra_plug"
version = "0.1.0"
description = ""
authors = ["tanigami <tanigami@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pfun = "^0.11.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
